name: CI - Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2



      - name: Build and start services with docker-compose
        run: |
          docker-compose build --parallel
          docker-compose up -d

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB on port 27017..."
          for i in {1..30}; do nc -z localhost 27017 && break || sleep 2; done

      - name: Wait for RabbitMQ
        run: |
          echo "Waiting for RabbitMQ management on port 15672..."
          for i in {1..30}; do nc -z localhost 15672 && break || sleep 2; done

      - name: Create .env file
        run: |
          echo "MONGODB_AUTH_URI=${{ secrets.MONGODB_PRODUCT_URI }}" >> auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
          echo "MONGODB_PRODUCT_URI=${{ secrets.MONGODB_PRODUCT_URI }}" >> product/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

      - name: Install dependencies
        run: |
          cd auth
          npm ci
          cd ..
          cd product
          npm ci
          cd ..
          npm ci
      - name: Run tests for auth
        run : |
          cd auth
          npm test
      - name: Run tests for product
        run: |
          cd auth &&
          npm start &
          cd product
          npm test


